spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/animais
    username: postgres
    password: admin
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: false
